try{
    hello()
}catch(error){
    console.error(error)
}

try{
    anotherfn()
}catch{
    console.log("Error here :/")
}